@startuml
|#skyblue|客户|
start
:申请服务;
|客户|
|#pink|业务经理|
if( 是新客户吗？ )then( Y )
    :登记客户信息;
    endif
:上门勘察;
:制定方案;
|业务经理|
|客户|
    if( 满意吗？ )then( Y )
        :签订合同;
|客户|
        fork
|业务经理|
             :安排工人;
        fork again
            :安排材料;
        end fork
        :填写派工单;
|业务经理|
|#orange|工人|
        :领取材料;
        :上门服务;
|工人|
|客户|
        :领取并填写反馈意见;
        :交回派工单;
|客户|
|服务人员|
        :结算收款;
        stop
|服务人员|
|客户|
    else( N )
        stop
|客户|
@enduml
