@startuml
autonumber
actor 读者 as d
actor 管理员 as g
participant 控制台 as c
database reader
database borrow
database fine
database book
d->g:我要还书
activate d
activate g
g-->d:请求读者号
d->g:返回读者号
g->c:登入系统
activate c
c->reader:查询读者
activate reader
reader-->c:返回结果
deactivate reader
c->borrow:查询借阅情况
activate borrow
borrow-->borrow:有未还书籍
activate borrow #orange
borrow->fine:查询罚金信息
activate fine
fine-->borrow:返回结果
deactivate fine
borrow-->c:显示罚金情况
deactivate borrow
borrow-->c:显示借阅记录
deactivate borrow
loop 归还N本书
g->c:归还书籍
activate borrow
c->borrow:移除所还书籍的borrow记录
activate book
borrow->book:书库记录加一
deactivate borrow
book-->c:归还成功
deactivate book
c-->g:归还成功
end
deactivate c
g-->d:归还成功
deactivate g
deactivate d
@enduml