@startuml
|管理员|
:输入读者借书卡;
|管理员|
|#AntiqueWhite|系统|
if(读者身份和借书条件是否满足要求?)then(否)
    :显示告警信息;
    stop
else(是)
    while(全部图书登记完毕？)
    :输入所借图书;
    :记录借书信息;
    :修改图书状态;
    :修改库存数量;
    :累加读者借书数量;
    endwhile
    :打印借书单;
    stop
endif
|系统|
@enduml