@startuml
left to right direction
skinparam handwritten true
skinparam usecase {
	BackgroundColor SkyBlue
	BorderColor DarkSlateGray
}
图书管理员 as gly
借阅者 as jyz
游客 as yk
yk <|-- jyz
rectangle 系统 {
  yk-->(图书查询)
  jyz-->(预定图书)
  jyz-->(取消预定)
  jyz-->(查询借阅情况)
  gly-->(借出图书)
  gly-->(归还图书)
  gly-->(维护书目)
  gly-->(维护读者信息)

  (预定图书).>(图书查询):include
  (取消预定).>(预定图书):include
  (登记罚款).>(归还图书):extends
}
@enduml